const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT 
global.appUrl=process.env.APP_URL || ""     // put your deploy app/bot url here, for 24/7 for (render , koyeb, glitch)
global.email ="tsuncca20@gmail.com"
global.location="Lahore,Pakistan."


global.mongodb= process.env.MONGODB_URI || "false"  
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "null"
global.DATABASE_URL = process.env.DATABASE_URL || "false"

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md-3";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029VagJIAr3bbVBCpEkAM07";
global.website =process.env.GURL || "https://whatsapp.com/channel/0029VagJIAr3bbVBCpEkAM07" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://i.ibb.co/TgwRyHR/Ephoto360-com-166de101e03cd7.jpg" || "https://i.ibb.co/bH1kbX0/a4c0b1af253197d4837ff6760d5b81c0.jpg" ; // SET LOGO FOR IMAGE 
global.caption = process.env.CAPTION || global.caption || "Made With LOVE!" 


global.devs = "" // Developer Contacts
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "923137183974";




//========================= [ BOT SETTINGS ] ======8===================\\
global.style = process.env.STYLE   || Math.floor(Math.random()*6) || '1'  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || process.env.CAN_GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || process.env.CAN_WELCOME || Math.floor(Math.random()*3)  === 1 ?  "true" : "false" ;  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3
global.disablepm = process.env.DISABLE_PM || "false"
global.disablegroup = process.env.DISABLE_GROUPS || "false", // disable bot in groups when public mode

global.MsgsInLog = process.env.MSGS_IN_LOG|| "false" // "true"  to see messages , "log" to show logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES || "" //"https://i.ibb.co/pXyNHj8/suhail.jpg" // "image" // set Image/video urls here
global.waPresence= process.env.WAPRESENCE ||  "null" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "true"
global.save_status = process.env.AUTO_SAVE_STATUS || "true"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd.onrender.com/" //  || "https://api-smd-1.vercel.app" // expires
global.scan = "https://suhail-md-vtsf.onrender.com";

global.SESSION_ID = process.env.SESSION_ID  || "SUHAIL_11_00_05_25_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTQ0LFxuICAgICAgICA1MyxcbiAgICAgICAgMTk0LFxuICAgICAgICAxNjcsXG4gICAgICAgIDM1LFxuICAgICAgICAxOTIsXG4gICAgICAgIDE0LFxuICAgICAgICAxOTYsXG4gICAgICAgIDE0NCxcbiAgICAgICAgNDMsXG4gICAgICAgIDIsXG4gICAgICAgIDIxMyxcbiAgICAgICAgMTk1LFxuICAgICAgICAxODMsXG4gICAgICAgIDE2NCxcbiAgICAgICAgMjE2LFxuICAgICAgICAyMDAsXG4gICAgICAgIDQ4LFxuICAgICAgICAyMTYsXG4gICAgICAgIDMzLFxuICAgICAgICAxMzIsXG4gICAgICAgIDEzNyxcbiAgICAgICAgNzYsXG4gICAgICAgIDMxLFxuICAgICAgICAxNjUsXG4gICAgICAgIDEyNSxcbiAgICAgICAgNjIsXG4gICAgICAgIDg1LFxuICAgICAgICAyMjIsXG4gICAgICAgIDE0NSxcbiAgICAgICAgMzMsXG4gICAgICAgIDY1XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE3NyxcbiAgICAgICAgMTE3LFxuICAgICAgICAyMDksXG4gICAgICAgIDcsXG4gICAgICAgIDQ2LFxuICAgICAgICAyMDgsXG4gICAgICAgIDIyMCxcbiAgICAgICAgMTAzLFxuICAgICAgICAyNCxcbiAgICAgICAgNjYsXG4gICAgICAgIDEzMSxcbiAgICAgICAgNDUsXG4gICAgICAgIDE1MyxcbiAgICAgICAgMTEwLFxuICAgICAgICAxMzEsXG4gICAgICAgIDIzOSxcbiAgICAgICAgMTYzLFxuICAgICAgICAxNzEsXG4gICAgICAgIDIyOCxcbiAgICAgICAgMjA4LFxuICAgICAgICAxNjIsXG4gICAgICAgIDE1OCxcbiAgICAgICAgODAsXG4gICAgICAgIDE5OCxcbiAgICAgICAgMTYzLFxuICAgICAgICAxNTcsXG4gICAgICAgIDIyOSxcbiAgICAgICAgMTIyLFxuICAgICAgICA1OSxcbiAgICAgICAgMTcwLFxuICAgICAgICAxNDAsXG4gICAgICAgIDIxXG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyXCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyMzIsXG4gICAgICAgIDIxNCxcbiAgICAgICAgMTA4LFxuICAgICAgICAxMjMsXG4gICAgICAgIDM4LFxuICAgICAgICAxNDYsXG4gICAgICAgIDIwMCxcbiAgICAgICAgMTc0LFxuICAgICAgICA5MyxcbiAgICAgICAgMjQ5LFxuICAgICAgICAxMjksXG4gICAgICAgIDQyLFxuICAgICAgICA3MixcbiAgICAgICAgMjQ3LFxuICAgICAgICAxODQsXG4gICAgICAgIDQzLFxuICAgICAgICAxODcsXG4gICAgICAgIDUwLFxuICAgICAgICAxODUsXG4gICAgICAgIDEwNCxcbiAgICAgICAgNDIsXG4gICAgICAgIDI0NCxcbiAgICAgICAgMTEsXG4gICAgICAgIDE3NixcbiAgICAgICAgMjIzLFxuICAgICAgICAxOTMsXG4gICAgICAgIDU1LFxuICAgICAgICAyNDUsXG4gICAgICAgIDIxNCxcbiAgICAgICAgMTM0LFxuICAgICAgICAyMzMsXG4gICAgICAgIDExNlxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA4MCxcbiAgICAgICAgMTU1LFxuICAgICAgICAxMjAsXG4gICAgICAgIDEyMSxcbiAgICAgICAgOTksXG4gICAgICAgIDk2LFxuICAgICAgICAxNjQsXG4gICAgICAgIDIzNCxcbiAgICAgICAgMixcbiAgICAgICAgMjMsXG4gICAgICAgIDI1NSxcbiAgICAgICAgNjksXG4gICAgICAgIDIzMixcbiAgICAgICAgMTI0LFxuICAgICAgICAxNCxcbiAgICAgICAgMTIwLFxuICAgICAgICAzNixcbiAgICAgICAgMjUzLFxuICAgICAgICAzNixcbiAgICAgICAgNzEsXG4gICAgICAgIDE5LFxuICAgICAgICAxNzcsXG4gICAgICAgIDEwNCxcbiAgICAgICAgOCxcbiAgICAgICAgMzIsXG4gICAgICAgIDE4NixcbiAgICAgICAgNzEsXG4gICAgICAgIDc3LFxuICAgICAgICA2NyxcbiAgICAgICAgMTU5LFxuICAgICAgICA4MyxcbiAgICAgICAgMzVcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkSWRlbnRpdHlLZXlcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDIyNCxcbiAgICAgICAgMTE4LFxuICAgICAgICAyMjcsXG4gICAgICAgIDc0LFxuICAgICAgICAyMjMsXG4gICAgICAgIDY1LFxuICAgICAgICA0MyxcbiAgICAgICAgMjIsXG4gICAgICAgIDIwOCxcbiAgICAgICAgNCxcbiAgICAgICAgMTQ0LFxuICAgICAgICAyMDAsXG4gICAgICAgIDEwLFxuICAgICAgICAyMjEsXG4gICAgICAgIDIwMCxcbiAgICAgICAgMTIsXG4gICAgICAgIDE0OSxcbiAgICAgICAgMjIwLFxuICAgICAgICAxMTEsXG4gICAgICAgIDEzNSxcbiAgICAgICAgMzAsXG4gICAgICAgIDIwNCxcbiAgICAgICAgNTcsXG4gICAgICAgIDE1OSxcbiAgICAgICAgMjQ5LFxuICAgICAgICAyNDksXG4gICAgICAgIDg5LFxuICAgICAgICA1MyxcbiAgICAgICAgMjA3LFxuICAgICAgICAyMDcsXG4gICAgICAgIDIxNyxcbiAgICAgICAgNzVcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTQ3LFxuICAgICAgICAyMDYsXG4gICAgICAgIDEzMyxcbiAgICAgICAgOTgsXG4gICAgICAgIDIzNixcbiAgICAgICAgMTkwLFxuICAgICAgICA5NyxcbiAgICAgICAgMjQ3LFxuICAgICAgICA1MSxcbiAgICAgICAgMjIyLFxuICAgICAgICA0NixcbiAgICAgICAgMTI3LFxuICAgICAgICAxMTcsXG4gICAgICAgIDE1NSxcbiAgICAgICAgMTI1LFxuICAgICAgICAxNTgsXG4gICAgICAgIDE0MSxcbiAgICAgICAgMTc5LFxuICAgICAgICAxOSxcbiAgICAgICAgMTgxLFxuICAgICAgICA1NSxcbiAgICAgICAgMTAwLFxuICAgICAgICAxNjQsXG4gICAgICAgIDE1NyxcbiAgICAgICAgOTksXG4gICAgICAgIDY4LFxuICAgICAgICAyMTksXG4gICAgICAgIDEyMSxcbiAgICAgICAgODEsXG4gICAgICAgIDE2OCxcbiAgICAgICAgMjMsXG4gICAgICAgIDQzXG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZFByZUtleVwiOiB7XG4gICAgXCJrZXlQYWlyXCI6IHtcbiAgICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDU2LFxuICAgICAgICAgIDMzLFxuICAgICAgICAgIDE4OSxcbiAgICAgICAgICAzNyxcbiAgICAgICAgICAyMTcsXG4gICAgICAgICAgODMsXG4gICAgICAgICAgMTEwLFxuICAgICAgICAgIDIxMyxcbiAgICAgICAgICAyNTEsXG4gICAgICAgICAgMTMwLFxuICAgICAgICAgIDEzMCxcbiAgICAgICAgICAxODAsXG4gICAgICAgICAgNzEsXG4gICAgICAgICAgODIsXG4gICAgICAgICAgNzcsXG4gICAgICAgICAgMTk2LFxuICAgICAgICAgIDExMCxcbiAgICAgICAgICAyMjAsXG4gICAgICAgICAgMjQ2LFxuICAgICAgICAgIDEwNyxcbiAgICAgICAgICAzMixcbiAgICAgICAgICAxNjIsXG4gICAgICAgICAgMTc5LFxuICAgICAgICAgIDEwNyxcbiAgICAgICAgICAxNzcsXG4gICAgICAgICAgNzYsXG4gICAgICAgICAgMTcwLFxuICAgICAgICAgIDE5MyxcbiAgICAgICAgICAyMzUsXG4gICAgICAgICAgNixcbiAgICAgICAgICA5NSxcbiAgICAgICAgICA4M1xuICAgICAgICBdXG4gICAgICB9LFxuICAgICAgXCJwdWJsaWNcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAzNCxcbiAgICAgICAgICAxMjcsXG4gICAgICAgICAgMTUsXG4gICAgICAgICAgMTQ3LFxuICAgICAgICAgIDE0NyxcbiAgICAgICAgICAxNTcsXG4gICAgICAgICAgMTYxLFxuICAgICAgICAgIDcxLFxuICAgICAgICAgIDcsXG4gICAgICAgICAgOTcsXG4gICAgICAgICAgOTQsXG4gICAgICAgICAgNjUsXG4gICAgICAgICAgMjQwLFxuICAgICAgICAgIDEyNixcbiAgICAgICAgICA0MixcbiAgICAgICAgICAxNTcsXG4gICAgICAgICAgMjA4LFxuICAgICAgICAgIDE0NCxcbiAgICAgICAgICAyNDcsXG4gICAgICAgICAgMTUxLFxuICAgICAgICAgIDE4NSxcbiAgICAgICAgICAyMjUsXG4gICAgICAgICAgNTYsXG4gICAgICAgICAgMjM5LFxuICAgICAgICAgIDcsXG4gICAgICAgICAgMTYyLFxuICAgICAgICAgIDExNixcbiAgICAgICAgICAxMDAsXG4gICAgICAgICAgMTc4LFxuICAgICAgICAgIDE3MSxcbiAgICAgICAgICAxMDAsXG4gICAgICAgICAgMzZcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH0sXG4gICAgXCJzaWduYXR1cmVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyMzEsXG4gICAgICAgIDE0NyxcbiAgICAgICAgMjksXG4gICAgICAgIDExMSxcbiAgICAgICAgMTIwLFxuICAgICAgICAyNDcsXG4gICAgICAgIDIyLFxuICAgICAgICA4MixcbiAgICAgICAgMTI0LFxuICAgICAgICAzOCxcbiAgICAgICAgMjIwLFxuICAgICAgICA3NyxcbiAgICAgICAgMTAxLFxuICAgICAgICAyOCxcbiAgICAgICAgMTE2LFxuICAgICAgICAxODksXG4gICAgICAgIDgyLFxuICAgICAgICAyMTksXG4gICAgICAgIDIwMixcbiAgICAgICAgMTEsXG4gICAgICAgIDIyNCxcbiAgICAgICAgMTgsXG4gICAgICAgIDE5MyxcbiAgICAgICAgMjIwLFxuICAgICAgICAyNDksXG4gICAgICAgIDQ4LFxuICAgICAgICAxMSxcbiAgICAgICAgMTgyLFxuICAgICAgICAyMjIsXG4gICAgICAgIDgwLFxuICAgICAgICAxNzAsXG4gICAgICAgIDE3MyxcbiAgICAgICAgNjAsXG4gICAgICAgIDEwMyxcbiAgICAgICAgMjksXG4gICAgICAgIDU5LFxuICAgICAgICAxNTcsXG4gICAgICAgIDEwNyxcbiAgICAgICAgMTkyLFxuICAgICAgICAxNTAsXG4gICAgICAgIDExOSxcbiAgICAgICAgMjE5LFxuICAgICAgICAxNzUsXG4gICAgICAgIDc4LFxuICAgICAgICAxNCxcbiAgICAgICAgNzgsXG4gICAgICAgIDg1LFxuICAgICAgICAyMTMsXG4gICAgICAgIDkyLFxuICAgICAgICA0OCxcbiAgICAgICAgMjQsXG4gICAgICAgIDEzNyxcbiAgICAgICAgMTI3LFxuICAgICAgICAxMzAsXG4gICAgICAgIDExMCxcbiAgICAgICAgMjA0LFxuICAgICAgICAxMjQsXG4gICAgICAgIDI1NCxcbiAgICAgICAgMjUyLFxuICAgICAgICAxMzMsXG4gICAgICAgIDksXG4gICAgICAgIDU2LFxuICAgICAgICAyMjEsXG4gICAgICAgIDEzMFxuICAgICAgXVxuICAgIH0sXG4gICAgXCJrZXlJZFwiOiAxXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uSWRcIjogMjM3LFxuICBcImFkdlNlY3JldEtleVwiOiBcIk4vV21FcjUycXdQZGM4a0pvM01pbWRpZnBKZ21wdWxWdVlvTDl6N2I4N3c9XCIsXG4gIFwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzXCI6IFtcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiOTIzMzYwMjQxMzY0QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCI0RUI5RUY4RTQ3ODY1Qjk1RDEwOTQyOTQwM0RGMUQ4RVwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3NDgxNzA4MTRcbiAgICB9LFxuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCI5MjMzNjAyNDEzNjRAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIjgyNTM4RDA3Q0ZENDI3QjZEQzMzQTY5RjlERkMyMTI3XCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTc0ODE3MDgxNFxuICAgIH1cbiAgXSxcbiAgXCJuZXh0UHJlS2V5SWRcIjogMzEsXG4gIFwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWRcIjogMzEsXG4gIFwiYWNjb3VudFN5bmNDb3VudGVyXCI6IDEsXG4gIFwiYWNjb3VudFNldHRpbmdzXCI6IHtcbiAgICBcInVuYXJjaGl2ZUNoYXRzXCI6IGZhbHNlXG4gIH0sXG4gIFwiZGV2aWNlSWRcIjogXCJjbUhSQVJIVFFtYTZ0QWZXUmlqNXZnXCIsXG4gIFwicGhvbmVJZFwiOiBcImI5Njg4OGU5LTg2MTgtNDAwNi04NTI1LWQxMTdiYjY2ZWY2Y1wiLFxuICBcImlkZW50aXR5SWRcIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAyMTcsXG4gICAgICA3OCxcbiAgICAgIDIyOSxcbiAgICAgIDU3LFxuICAgICAgMTU3LFxuICAgICAgMTE4LFxuICAgICAgMTUwLFxuICAgICAgMzcsXG4gICAgICA0NSxcbiAgICAgIDE0LFxuICAgICAgMjAxLFxuICAgICAgMTUyLFxuICAgICAgNDIsXG4gICAgICAxOTIsXG4gICAgICAxODUsXG4gICAgICAxMDgsXG4gICAgICAxMzEsXG4gICAgICAzNCxcbiAgICAgIDEwNyxcbiAgICAgIDE0NVxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RlcmVkXCI6IGZhbHNlLFxuICBcImJhY2t1cFRva2VuXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMTQ0LFxuICAgICAgMTE4LFxuICAgICAgNjksXG4gICAgICA4NixcbiAgICAgIDI0MixcbiAgICAgIDI0NyxcbiAgICAgIDE3LFxuICAgICAgMTg4LFxuICAgICAgMTA3LFxuICAgICAgMTYsXG4gICAgICAyMTIsXG4gICAgICA0MCxcbiAgICAgIDUyLFxuICAgICAgNSxcbiAgICAgIDEwNixcbiAgICAgIDE2MCxcbiAgICAgIDE2NSxcbiAgICAgIDE2NixcbiAgICAgIDI0NixcbiAgICAgIDE3MlxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25cIjoge30sXG4gIFwiYWNjb3VudFwiOiB7XG4gICAgXCJkZXRhaWxzXCI6IFwiQ0lLdjdza0VFTGp3eThFR0dBSWdBQ2dBXCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlS2V5XCI6IFwiT2piZnhWeXRERWxuaVBrWWJuVDkxOUY1VDVneHU3YWVDbTA2SnFjU25rdz1cIixcbiAgICBcImFjY291bnRTaWduYXR1cmVcIjogXCJRaUtjYnNlWnJDT1M2QTUxa1B0RFV2bXpFcVREeWwxQ2EvTGtBUU5jQ1MxSEtOV0ROL0hPZUxVN2JJUjJWVXFJSEQ0MGw0Sm9wUytTQW5JN2d1VmhBdz09XCIsXG4gICAgXCJkZXZpY2VTaWduYXR1cmVcIjogXCJCV1FKYTB2bEtSdm1KOXVYdk9WazFSOHJQVWF0NFZEaFQvN3lrTW5ZQ0FVK3lDSWgwNkN6bkw4YTMwYzEvNDJLaVI2M1FHUHhCR1lZWURPWkh4cU1ndz09XCJcbiAgfSxcbiAgXCJtZVwiOiB7XG4gICAgXCJpZFwiOiBcIjkyMzM2MDI0MTM2NDoxN0BzLndoYXRzYXBwLm5ldFwiLFxuICAgIFwibmFtZVwiOiBcIk5veXNcIixcbiAgICBcImxpZFwiOiBcIjEwNTkyNzM2NTY0ODU3NjoxN0BsaWRcIlxuICB9LFxuICBcInNpZ25hbElkZW50aXRpZXNcIjogW1xuICAgIHtcbiAgICAgIFwiaWRlbnRpZmllclwiOiB7XG4gICAgICAgIFwibmFtZVwiOiBcIjkyMzM2MDI0MTM2NDoxN0BzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImRldmljZUlkXCI6IDBcbiAgICAgIH0sXG4gICAgICBcImlkZW50aWZpZXJLZXlcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA1LFxuICAgICAgICAgIDU4LFxuICAgICAgICAgIDU0LFxuICAgICAgICAgIDIyMyxcbiAgICAgICAgICAxOTcsXG4gICAgICAgICAgOTIsXG4gICAgICAgICAgMTczLFxuICAgICAgICAgIDEyLFxuICAgICAgICAgIDczLFxuICAgICAgICAgIDEwMyxcbiAgICAgICAgICAxMzYsXG4gICAgICAgICAgMjQ5LFxuICAgICAgICAgIDI0LFxuICAgICAgICAgIDExMCxcbiAgICAgICAgICAxMTYsXG4gICAgICAgICAgMjUzLFxuICAgICAgICAgIDIxNSxcbiAgICAgICAgICAyMDksXG4gICAgICAgICAgMTIxLFxuICAgICAgICAgIDc5LFxuICAgICAgICAgIDE1MixcbiAgICAgICAgICA0OSxcbiAgICAgICAgICAxODcsXG4gICAgICAgICAgMTgyLFxuICAgICAgICAgIDE1OCxcbiAgICAgICAgICAxMCxcbiAgICAgICAgICAxMDksXG4gICAgICAgICAgNTgsXG4gICAgICAgICAgMzgsXG4gICAgICAgICAgMTY3LFxuICAgICAgICAgIDE4LFxuICAgICAgICAgIDE1OCxcbiAgICAgICAgICA3NlxuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICBdLFxuICBcInBsYXRmb3JtXCI6IFwic21iYVwiLFxuICBcImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcFwiOiAxNzQ4MTcwODEyLFxuICBcIm15QXBwU3RhdGVLZXlJZFwiOiBcIkFBQUFBSytwXCJcbn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFLKzAuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJSSGw1dEdEUnZaTWJpaFgvWVVLMGdiSkNJT3M3NmU0dVVtU1I3RFptSGhjPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjEyMjg2NDIxNzgsXCJjdXJyZW50SW5kZXhcIjoxLFwiZGV2aWNlSW5kZXhlc1wiOlswLDFdfSxcInRpbWVzdGFtcFwiOlwiMTc0ODE2NjMzOTA3NFwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUsrby5qc29uIjogIntcImtleURhdGFcIjpcIkRnMUJuNlRZVWNnNzBHZFE1WG9pRHdpVHBxOTNPbitKa2hjN0t4VU1SR0E9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTIyODY0MjE3NSxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIwXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBSytwLmpzb24iOiAie1wia2V5RGF0YVwiOlwiWlF5clROcFRmK2ZscXZJSlVWSmozenNvT0pDOHA5V05TaS9Pak1hcHpXQT1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxMjI4NjQyMTc1LFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMF19LFwidGltZXN0YW1wXCI6XCIxNzQ2OTY3NTgyMjAwXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBSytxLmpzb24iOiAie1wia2V5RGF0YVwiOlwidk9DUFBBd3FjZnZ1ZWRpeXJxL29teERORmFXS0lrQ0pZRFV4MFE4aVlMQT1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxMjI4NjQyMTc2LFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjBcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFLK3IuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJRb2lVN0toTXJ6blNsUC8zd0pwUEFYLzNMQ3gzRHdQWERkcklHSy9LLy9zPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjEyMjg2NDIxNzYsXCJjdXJyZW50SW5kZXhcIjozLFwiZGV2aWNlSW5kZXhlc1wiOlswLDEsM119LFwidGltZXN0YW1wXCI6XCIwXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBSytzLmpzb24iOiAie1wia2V5RGF0YVwiOlwiWEhKOWtCbXRMWmNZOHduaFJmczJSTUpFY3Q4N0liMGE4SSt1bWpMOWVtYz1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxMjI4NjQyMTc2LFwiY3VycmVudEluZGV4XCI6MyxcImRldmljZUluZGV4ZXNcIjpbMCwzXX0sXCJ0aW1lc3RhbXBcIjpcIjBcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFLK3QuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCIxdXhGMlJkSGtVYlZGeWRrY21zSVd3VzBndHZMV0xPeDc3S1BvZWtuL0pFPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjEyMjg2NDIxNzYsXCJjdXJyZW50SW5kZXhcIjo0LFwiZGV2aWNlSW5kZXhlc1wiOlswLDNdfSxcInRpbWVzdGFtcFwiOlwiMFwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUsrdS5qc29uIjogIntcImtleURhdGFcIjpcIlBLWmtIRndJbFozNkgyTTFNeGpEbnFJbFBGRU1lczhHZ1NvUmExeU5sdzA9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTIyODY0MjE3NixcImN1cnJlbnRJbmRleFwiOjQsXCJkZXZpY2VJbmRleGVzXCI6WzBdfSxcInRpbWVzdGFtcFwiOlwiMTc0Nzg2NTE0NDkxNFwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUsrdi5qc29uIjogIntcImtleURhdGFcIjpcIkkyU0tNQnpSSGFNM1QxbzJOYXAxeHVGK2R2WWhoSGdlQStPa2FpOUErWjg9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTIyODY0MjE3NyxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIwXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBSyt3Lmpzb24iOiAie1wia2V5RGF0YVwiOlwiWWxQWHhiYkRyZThaUTNrMXIvNlRadTlXQlVhWW9NSEtKQkk2NUkyN3ZtRT1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxMjI4NjQyMTc3LFwiY3VycmVudEluZGV4XCI6MyxcImRldmljZUluZGV4ZXNcIjpbMCwxLDJdfSxcInRpbWVzdGFtcFwiOlwiMFwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUsreC5qc29uIjogIntcImtleURhdGFcIjpcInJFV05CTHVQUURrQ1Z3b3ZEbm9rTWNWSStxM2F6WU51SEJieVAycFhtVFk9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTIyODY0MjE3NyxcImN1cnJlbnRJbmRleFwiOjQsXCJkZXZpY2VJbmRleGVzXCI6WzAsMSwyXX0sXCJ0aW1lc3RhbXBcIjpcIjBcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFLK3kuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJ4WWRDL1QzV1NGRjB1RVFnWE1jdC9OclhFdEhvbnpDaTZ3LzBycnd3TzVFPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjEyMjg2NDIxNzcsXCJjdXJyZW50SW5kZXhcIjo0LFwiZGV2aWNlSW5kZXhlc1wiOlswLDJdfSxcInRpbWVzdGFtcFwiOlwiMFwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUsrei5qc29uIjogIntcImtleURhdGFcIjpcIkdOQnpSTHJTVEJVaDdBQXpSUVVJUmozRVc2cGJKZitCUW81VERCT01STWc9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTIyODY0MjE3NyxcImN1cnJlbnRJbmRleFwiOjQsXCJkZXZpY2VJbmRleGVzXCI6WzBdfSxcInRpbWVzdGFtcFwiOlwiMTc0ODE2NjMyNTYwOFwifSIKfQ=="  // PUT your SESSION_ID 


module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "3.0.1-developement",
  caption : global.caption || "" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ GlobalTechInfo ® 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@GlobalTechInfo"),
 
  author : process.env.PACK_AUTHER|| "°【.ISHU.】",
  packname: process.env.PACK_NAME || "【〆༯𝙎ค૯𝙀𝘿】✘",
  botname : process.env.BOT_NAME  || "SAEED-MD",
  ownername:process.env.OWNER_NAME|| "SAEED:Shy<3",


  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "Vg22QDgXcjUWKS9V2apAYVpC",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "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",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,


  WORKTYPE: process.env.WORKTYPE || process.env.MODE|| "private",
  LANG: ( process.env.THEME ||  "SUHAIL"  ).toUpperCase(),



};



global.ELEVENLAB_API_KEY = process.env.ELEVENLAB_API_KEY || "";
global.aitts_Voice_Id = process.env.AITTS_ID|| "37";





















global.rank = "updated"
global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
  //aitts_Voice_Id : process.env.AITTS_ID || "37",
  //ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY  || "",
